package '需求' {
    requirement '任务需求' {
        requirement '性能' {
            requirement '天气' {
                doc /*
                     * 在少量云雾中可以工作
                     */
            }
            requirement '可见性' {
                doc /*
                     * 50 米的可见性
                     */
            }
            requirement '地理位置精度' {
                doc /* 1 km 的地理位置精度*/
            }
        }
        requirement '覆盖范围' {}
    }
}