package '辅助元素.接口' {

    package '信号' {
        item def <SpacecraftSeparationCommand> '飞船分离指令' ;
        item def <SpacecraftSeparationComplete> '飞船分离完成' ;
        item def <GroundCmdSafe> '地面指令安全';
        item def <AutonomouseSafe> '自主安全';
        item def <Launch> '发射';
        item def <OnOrbit> '在轨';
        item def <SensorOnCommand> '探测器开启指令';
        item def <DeorbitComplete> '脱轨完成';
    }
}